#!/usr/bin/env bash

# shellcheck disable=SC1091
source "$HOME/.dotfiles/profiles/profile1-base"
source "$HOME/.dotfiles/profiles/profile2-defaults"
source "$HOME/.dotfiles/profiles/profile2-pass"
source "$HOME/.dotfiles/profiles/profile4-helper"
source "$HOME/.dotfiles/profiles/profile4-tests"
source "$HOME/.dotfiles/profiles/profile5-ansible"
source "$HOME/.dotfiles/profiles/profile5-containers"
source "$HOME/.dotfiles/profiles/profile5-git"
source "$HOME/.dotfiles/profiles/profile6-other"
