#!/usr/bin/env bash

VM_SEC_USER_AGENT=${VM_SEC_USER_AGENT:-'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:147.0) Gecko/20100101 Firefox/147.0'}


######################################################################
##
## HELPER:: default
##
######################################################################
get_distro() {
    if [[ -f /etc/os-release ]]; then
        local id
        id=$(grep '^ID=' /etc/os-release | cut -d= -f2 | tr -d '"')
        if [[ -n "$id" ]]; then
            echo "${id}"
            return
        fi
    fi
    echo "linux"
}
get_distro_version() {
    if [[ -f /etc/os-release ]]; then
        local id version
        id=$(grep '^ID=' /etc/os-release | cut -d= -f2 | tr -d '"')
        version=$(grep '^VERSION_ID=' /etc/os-release | cut -d= -f2 | tr -d '"')
        if [[ -n "$id" && -n "$version" ]]; then
            echo "${id}:${version}"
            return
        fi
    fi
    echo "linux:unknown"
}

######################################################################
##
## HELPER:: converter
##
######################################################################
vm_sec_encode_utf8() {
  if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <STRING>"
    return 1
  fi
  printf '%s' "$1" | xxd -p -u | sed 's/\(..\)/\\x\1/g'
}

vm_sec_encode_utf16() {
  if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <STRING>"
    return 1
  fi
  printf '%s' "$1" | iconv -f UTF-8 -t UTF-16LE | xxd -p | sed 's/\(..\)\(..\)/\\u{\2\1}/g' | sed 's/\\u{00\([0-9a-fA-F]\{2\}\)}/\\u{\1}/g'
}

vm_sec_encode_base64() {
  if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <STRING>"
    return 1
  fi
  echo -n "$1" | base64
}
