#!/usr/bin/env bash

# shellcheck disable=SC2034
VM_SEC_LISTS_SECLISTS="$HOME/opt/sec/SecLists"
# shellcheck disable=SC2034
VM_SEC_LISTS_PAYLOADS="$HOME/opt/sec/PayloadsAllTheThings"
# shellcheck disable=SC2034
VM_SEC_LISTS_SECFILES="$HOME/opt/sec/SecFiles"
# shellcheck disable=SC2034
VM_SEC_LISTS_TEMPLATES="$HOME/opt/sec/Templates"
# shellcheck disable=SC2034
VM_SEC_NUCLEI_TEMPLATES="$HOME/.dotfiles/sec/nuclei"

VM_SEC_USER_AGENT=${VM_SEC_USER_AGENT:-'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:147.0) Gecko/20100101 Firefox/147.0'}

# shellcheck disable=SC1091
source "$HOME/.dotfiles/profiles/profile-sec-base"
# shellcheck disable=SC1091
source "$HOME/.dotfiles/profiles/profile-sec-helper"
# shellcheck disable=SC1091
source "$HOME/.dotfiles/profiles/profile-sec-check"
# shellcheck disable=SC1091
source "$HOME/.dotfiles/profiles/profile-sec-api"
# shellcheck disable=SC1091
source "$HOME/.dotfiles/profiles/profile-sec-tools"
