#!/usr/bin/env bash

### SSH ###
vm_xterm_cp_ssh() {
  if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <SSH_HOST>"
    return 1
  fi
  infocmp -x | ssh "$1" -- tic -x -
}
vm_xterm_cp_local() {
  local term_dir term_path
  term_dir=$(echo "$TERM" | cut -c1)
  term_path="${TERMINFO:-$HOME/.terminfo}/$term_dir/$TERM"

  if [ ! -f "$term_path" ]; then
    echo "Terminfo for $TERM not found at $term_path"
    return 1
  fi
  sudo install -D "$term_path" "/etc/terminfo/$term_dir/$TERM"
}

### General ###
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
man() {
  LESS_TERMCAP_mb=$'\e[1;31m' \
  LESS_TERMCAP_md=$'\e[1;31m' \
  LESS_TERMCAP_me=$'\e[0m' \
  LESS_TERMCAP_se=$'\e[0m' \
  LESS_TERMCAP_so=$'\e[1;33;44m' \
  LESS_TERMCAP_ue=$'\e[0m' \
  LESS_TERMCAP_us=$'\e[4;1;32m' \
  LESS_TERMCAP_mr=$'\e[7m' \
  LESS_TERMCAP_mh=$'\e[2m' \
  LESS_TERMCAP_ZN=$'\e[74m' \
  LESS_TERMCAP_ZV=$'\e[75m' \
  LESS_TERMCAP_ZO=$'\e[73m' \
  LESS_TERMCAP_ZW=$'\e[75m' \
  GROFF_NO_SGR=1 \
  /usr/bin/man "$@"
}
mann() {
  man "$@" | batcat -l man --style=-numbers
}

### LS as EZA ###
check_command_q eza && alias ls='eza --color=always --git'
alias l='ls -a1'
alias ll='ls -aalhg'
alias lll='ll -muU --time-style long-iso'
alias lg='ll --grid'
alias llm='ll -t modified -s modified'
alias lla='ll -t accessed -s accessed'
alias llc='ll -t created -s created'
alias ld='ls -ld .*'
alias tree='ls -TlgL 4'

### CAT as BAT ###
alias catt='batcat -p -P --color always'
alias catt-b='batcat -P --color always'

### CP as RSYNC ###
alias rsync-d='rsync --info=progress2 -az --no-o --no-g --no-perms --no-times --stats'
alias cp-r='rsync-d -u'
alias cp-ra='rsync-d'
scp-r() {
  rsync-d -u -e "ssh -T -o Compression=no -x" "$@"
}
scp-ra() {
  rsync-d -e "ssh -T -o Compression=no -x" "$@"
}

### GREP ###
alias grep='grep --color'
alias grep-r='grep -rawi'
alias grep-rq='grep -rawih'
alias grep-rr='grep -Rai'
alias grep-rrq='grep -Raih'
alias grep-d='grep -r -n -H -C 5 --exclude-dir={.git,.svn,CVS}'
if check_command_q rg; then
  # https://github.com/BurntSushi/ripgrep
  alias rg-r='rg -wi'
  alias rg-rq='rg -wiIN'
  alias rg-d='rg -n -H -C 5 --glob "!.git/*" --glob "!.svn/*" --glob "!CVS/*"'
  alias rg-github='rg -ioPIN "https://github\.com/[^/\s]+/[^/\s]+" | sort -h | uniq'
fi

### FIND ###
# https://github.com/sharkdp/fd
check_command_q fdfind && alias fd='fdfind --hidden --no-ignore'
alias find-no='sudo /usr/bin/find / -nouser -o -nogroup -ls 2>/dev/null'
find-g() {
  sudo /usr/bin/find / \
    -not -regex '/home/.*' \
    -not -regex '/mnt/.*' \
    -not -regex '/media/.*' \
    -not -regex '.*/\.cache/.*' \
    -not -regex '/proc/.*' \
    -not -regex '/sys/.*' \
    -not -regex '/var/log/.*' \
    -newermt "-${1:-5} minute" -ls 2>/dev/null
}
find-l() {
  /usr/bin/find "${2:-.}" \
    -not -regex "${3:-x}" \
    -newermt "-${1:-5} minute" -ls 2>/dev/null
}

### OTHER ###
alias t='tail -f'
alias du-l='du -hs * .* 2>/dev/null | sort -h'
alias du-g='du -hs /boot /dev /etc /home /opt /root /snap /srv /sys /tmp /usr /var 2>/dev/null | sort -h'
alias ip='ip -c'
alias watch-q='watch -n.5 -d'

### VIM ###
check_command_q nvim && alias vim=nvim
check_command_q nvim && alias vimdiff='nvim -d'


### TMUX ###
alias vm_tl='tmux ls'
alias vm_ta='tmux attach -t'
alias vm_tk='tmux kill-session -t'

### ZED ###
check_command_q flatpak && alias zed-editor='flatpak run dev.zed.Zed'

### COMPRESS ###
check_command_q pigz && alias pigz='pigz -k -p$(nproc)'

tar-p() {
  if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <directory> [<password | 'pw'>]"
    return 1
  fi
  check_command tar || return 1
  check_command pigz || return 1
  check_command gpg || return 1

  local PATH_TO_ENC="$1"
  if [ $# -eq 1 ]; then
    echo "disabled"
    tar --use-compress-program="pigz " -cpf "$(basename "$PATH_TO_ENC").tar.gz" -C "$PATH_TO_ENC" .
  elif [ $# -eq 2 ]; then
    local PASSWORD_FOR_ENC="$2"
    [[ "$PASSWORD_FOR_ENC" == "pw" ]] && { # pragma: allowlist secret
      echo "Password: "
      read -rs PASSWORD_FOR_ENC
    }
    tar --use-compress-program="pigz " -cpf - -C "$PATH_TO_ENC" . | gpg -c --cipher-algo AES256 --batch --passphrase "$PASSWORD_FOR_ENC" -o "$(basename "$PATH_TO_ENC").tar.gz.gpg.enc"
  fi
}
untar-p() {
  if [ "$#" -lt 2 ]; then
    echo "Usage: $0 <encrypted_file> <password | 'pw'>"
    return 1
  fi
  check_command tar || return 1
  check_command pigz || return 1
  check_command gpg || return 1

  local PATH_TO_DEC="$1"
  local PASSWORD_FOR_DEC="$2"
  [[ "$PASSWORD_FOR_DEC" == "pw" ]] && { # pragma: allowlist secret
    echo "Password: "
    read -rs PASSWORD_FOR_DEC
  }

  mkdir -p "$(dirname "$PATH_TO_DEC")/${PATH_TO_DEC%%.*}"
  gpg -d --batch --passphrase "$PASSWORD_FOR_DEC" "$PATH_TO_DEC" | tar --use-compress-program="pigz " -xpf - -C "$(dirname "$PATH_TO_DEC")/${PATH_TO_DEC%%.*}"
}
