#!/usr/bin/env bash

VM_SEC_LISTS_SECLISTS="$HOME/opt/sec/SecLists"
VM_SEC_USER_AGENT=${VM_SEC_USER_AGENT:-'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:147.0) Gecko/20100101 Firefox/147.0'}

######################################################################
##
## DEFAULTS:: extender
##
######################################################################
# shellcheck disable=SC2139
alias nuclei="nuclei -header 'User-Agent: ${VM_SEC_USER_AGENT}'"

# shellcheck disable=SC2139
alias sj="sj -a '${VM_SEC_USER_AGENT}'"
alias sqlmap="sqlmap --random-agent"
# shellcheck disable=SC2139
alias rustscan="rustscan -u '${VM_SEC_USER_AGENT}'"

######################################################################
##
## FUNCTIONS:: tools
##
######################################################################

alias vm_sec_server='python3 -m http.server 4445'
alias vm_sec_tunnel='ngrok http 4445'

######################################################################
##
## FUNCTIONS:: tools :: NMAP
##
######################################################################
# -Pn -sS -T4
alias vm_sec_nmap_ssl='mkdir -p nmap && sudo nmap -vv -p 443 --script "ssl-enum-ciphers"'
alias vm_sec_nmap_quick='mkdir -p nmap && sudo nmap -vv -sC -oA nmap/scan1'
alias vm_sec_nmap_deep='mkdir -p nmap && sudo nmap -vv -sC -sV -O -oA nmap/scan2 --script "nmap-vulners/,vulscan/"'

xsltproc() {
  local NMAP_REPORT_ID="${1:-1}"
  mkdir -p /var/log/nmap
  xsltproc \
    -o "/var/log/nmap/report-$(date +%Y-%m-%d)-${NMAP_REPORT_ID}.html" \
    /opt/nmap/nmap-bootstrap.xsl \
    "/var/log/nmap/report-$(date +%Y-%m-%d)-${NMAP_REPORT_ID}.xml" \
    "$@"
}
nmap-report() {
  local NMAP_REPORT_ID="${1:-1}"
  mkdir -p /var/log/nmap
  nmap -oA /var/log/nmap/report-"$(date +%Y-%m-%d)"-"${NMAP_REPORT_ID}" "$@"
  xsltproc
}

######################################################################
##
## FUNCTIONS:: tools
##
######################################################################
# shellcheck disable=SC2139
alias vm_sec_massdns="massdns -r '${VM_SEC_LISTS_SECLISTS}/massdns/lists/resolvers.txt' -t A -o S targets.txt -w hosts.txt -s 4000"
alias vm_sec_what="whatweb -v"

vm_sec_xssall() {
  command -v gum >/dev/null 2>&1 || { echo "gum is not installed"; return 1; }
  command -v httpx >/dev/null 2>&1 || { echo "httpx is not installed"; return 1; }
  command -v katana >/dev/null 2>&1 || { echo "katana is not installed"; return 1; }
  command -v dalfox >/dev/null 2>&1 || { echo "dalfox is not installed"; return 1; }
  gum input --placeholder='Input Target IP/DOMAIN' |
    httpx -silent |
    katana -silent |
    dalfox pipe --silence
}

# echo https://192.168.111.41 | katana -jc -f qurl -d 5 -c 50 -kf robotstxt,sitemapxml -silent | dalfox pipe --skip-bav | grep "=" | egrep -iv ".(jpg|jpeg|gif|css|tif|tiff|png|ttf|woff|woff2|ico|pdf|svg|txt|js)" | unew
# echo https://192.168.111.41 | katana -jc -d 5 -c 50 -ef css,woff,woff2,eot,ttf,tiff,tif -kf robotstxt,sitemapxml | grep -v -e "="
# subfinder -d https://192.168.111.41 -silent -all | httpx -silent | katana -d 5 silent -em js,jsp,json | grep -P "(?i).+\.js(?:on|p)?$"

# shellcheck disable=SC2139
alias vm_sec_gobuster="gobuster dir --wordlist '${VM_SEC_LISTS_SECLISTS}/diccnoext.txt' --wildcard --url"

# shellcheck disable=SC2139
alias vm_sec_fuzz="ffuf -w '${VM_SEC_LISTS_SECLISTS}/content_discovery_all.txt' -mc all -u"
vm_sec_fuzz_path() {
  if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <[http(s)://]HOST>"
    return 1
  fi
  command -v ffuf >/dev/null 2>&1 || { echo "ffuf is not installed"; return 1; }

  # Check if the URL contains http or https
  if [[ "$1" =~ ^https?:// ]]; then
    # Extract protocol and domain
    protocol=$(echo "$1" | awk -F'://' '{print $1}')
    domain=$(echo "$1" | awk -F'://' '{print $2}')
  else
    # Default to https if no protocol is found
    protocol="https"
    domain="$1"
  fi

  ffuf -u "${protocol}://${domain}/FUZZ" \
    -w "${VM_SEC_LISTS_SECLISTS}/Discovery/Web-Content/common.txt" \
    -c -ac -recursion
}
vm_sec_fuzz_dns() {
  if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <[http(s)://]HOST>"
    return 1
  fi
  command -v ffuf >/dev/null 2>&1 || { echo "ffuf is not installed"; return 1; }

  # Check if the URL contains http or https
  if [[ "$1" =~ ^https?:// ]]; then
    # Extract protocol and domain
    protocol=$(echo "$1" | awk -F'://' '{print $1}')
    domain=$(echo "$1" | awk -F'://' '{print $2}')
  else
    # Default to https if no protocol is found
    protocol="https"
    domain="$1"
  fi

  ffuf -u "${protocol}://${domain}" \
    -w "${VM_SEC_LISTS_SECLISTS}/Discovery/DNS/namelist.txt" \
    -H "Host: ${protocol}://FUZZ.${domain}"
}

vm_sec_katana() {
  if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <TODO>"
    return 1
  fi
  command -v katana >/dev/null 2>&1 || { echo "katana is not installed"; return 1; }

  echo "$1" | katana -headless -fs rdn -d 1 -ct 1 -rl 10 -o result.txt -jsonl
}

alias vm_sec_sj="sj -i"

# https://pentest-tools.com/website-vulnerability-scanning/website-scanner
alias vm_sec_scan_ptt='docker run --rm -it pentesttoolscom/ptt-scan:latest run website_scanner'
# https://github.com/wpscanteam/wpscan
# --plugins-detection aggressive
alias vm_sec_scan_wpscan='docker run --rm -it wpscanteam/wpscan:latest --rua -e ap,at,tt,cb,dbe,u,m --url'

######################################################################
##
## FUNCTIONS:: tools
##
######################################################################
vm_sec_attack_sql() {
  if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <HOST_PATH>"
    return 1
  fi
  command -v sqlmap >/dev/null 2>&1 || { echo "sqlmap is not installed"; return 1; }

  local HOST_PATH="$1"
  local TODO_1="${2:id}"
  local TODO_2="${3:mysql}"
  local TODO_3="${4:10}"

  # TODO: extend with 'proxychains'
  sqlmap -u "$HOST_PATH" --dbs --batch -p "$TODO_1" --random-agent --tamper=between,space2comment --dbms="$TODO_2" --tech=B --no-cast --flush-session --threads "$TODO_3"
  # --level 5 --risk 3
}


######################################################################
##
## FUNCTIONS:: tools
##
######################################################################
vm_sec_ettercap(){
  if [ "$#" -lt 3 ]; then
    echo "Usage: $0 <INTERFACE> <IP-ADDRESS-HOST> <IP-ADDRESS-TARGET>"
    return 1
  fi
  command -v etthercap >/dev/null 2>&1 || { echo "etthercap is not installed"; return 1; }

  local iface="$1"
  local ip_h="$2"
  local ip_t="$3"

  sudo etthercap -T \
  -i "$iface" \
  --mitm arp \
  "/$ip_h//" \
  "/$ip_t//"
}
