#!/usr/bin/env bash

### COLOR ### (https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux)
# shellcheck disable=SC2034
NC='\033[0m'         # No Color
BRED='\033[1;31m'    # Red
BPURPLE='\033[1;35m' # Purple

### PY & ANSIBLE ###
export PY_COLOR=1
export ANSIBLE_FORCE_COLOR=1

### ZSH ###
if command -v zsh >/dev/null 2>&1 && [ -n "$ZSH_NAME" ]; then
  setopt NO_NOMATCH
fi

### BASH ###
export HISTTIMEFORMAT="%F %T "
alias sudo-env='sudo -E env "PATH=$PATH"'

### EDITOR ###
if command -v nvim >/dev/null 2>&1; then
  export EDITOR='nvim'
  export SUDO_EDITOR="nvim"
elif command -v vim >/dev/null 2>&1; then
  export EDITOR='vim'
  export SUDO_EDITOR="vim"
fi

######################################################################
##
## HELPER
##
######################################################################
add_to_path() {
  if [[ ":$PATH:" != *":$1:"* ]]; then
    export PATH="$PATH:$1"
  fi
}
add_to_path_front() {
  if [[ ":$PATH:" != *":$1:"* ]]; then
    export PATH="$1:$PATH"
  fi
}

check_command() {
  command -v "$1" >/dev/null 2>&1 || { echo "[WARN] Command '$1' is not installed!"; return 1; }
}
check_command_q() {
  command -v "$1" >/dev/null 2>&1 || return 1
}

is_snap_installed() {
  snap list "$1" >/dev/null 2>&1
}

######################################################################
##
## set PATH so it includes user's private bin if it exists
##
######################################################################
add_to_path_front "$HOME/.local/bin"
if [ -d "$HOME/.local/bin/vm" ]; then
  add_to_path_front "$HOME/.local/bin/vm"
fi
if [ -d /etc/zsh/profile.d ]; then
  if ls /etc/zsh/profile.d/*.sh 1>/dev/null 2>&1; then
    for i in /etc/zsh/profile.d/*.sh; do
      if [ -r "$i" ]; then
        # shellcheck disable=SC1090
        . "$i"
      fi
    done
    unset i
  fi
fi

######################################################################
##
## set PATH for dev env
##
######################################################################
# sudo snap install go --classic
if is_snap_installed go; then
  export GOPATH="$HOME/.go"
  #add_to_path '/usr/local/go/bin'
  add_to_path "$GOPATH/bin"
fi

# sudo snap install node --classic
if is_snap_installed node; then
  NPM_PACKAGES="${HOME}/.npm-packages"
  if [[ ":$PATH:" != *":$NPM_PACKAGES/share/man:"* ]]; then
    export MANPATH="${MANPATH-$(manpath)}:$NPM_PACKAGES/share/man"
  fi
  add_to_path_front '/snap/node/current/bin'
  add_to_path "$NPM_PACKAGES/bin"
fi

# sudo snap install ruby --classic
if is_snap_installed ruby; then
  export GEM_HOME="$HOME/.gems"
  add_to_path "$GEM_HOME/bin"
fi

# sudo snap install rustup --classic
if is_snap_installed rustup; then
  export RUSTUP_HOME="$HOME/.rustup"
  # add_to_path "$RUSTUP_HOME/bin"
  add_to_path "$HOME/.cargo/bin"
fi

# sudo snap install openjdk
if is_snap_installed openjdk; then
  export JAVA_HOME="/snap/openjdk/current/jdk"
  add_to_path "$JAVA_HOME/bin"
fi
