#!/usr/bin/env bash

### TESTS ###
vm_test_curl() {
  if [[ -z "$1" ]]; then
    echo "Usage: $0 <URL>"
    return 1
  fi
  check_command curl || return 1

  local user_agent='Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:147.0) Gecko/20100101 Firefox/147.0'
  curl -sSfL -o /dev/null \
    -H "User-Agent: $user_agent" \
    -w \
    "dns_lookup: %{time_namelookup}s :: connect: %{time_connect}s :: appconnect: %{time_appconnect}s :: pretransfer: %{time_pretransfer}s :: starttransfer: %{time_starttransfer}s\n-------------------------------\ntotal: %{time_total}s http_code: %{http_code}\n" \
    "$1"
}
vm_quick_iperf() {
  if command -v docker >/dev/null 2>&1; then
    docker run -d -it --rm --name=iperf3-server -p 5201:5201 networkstatic/iperf3 -s
  elif command -v iperf3 >/dev/null 2>&1; then
    iperf3 -s
  else
    echo "[WARN] Command 'iperf3' and 'docker' are not installed!"
    return 1
  fi
}
alias vm_test_speed_pub_py='curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python3 - --secure'
