#!/usr/bin/env bash

### TESTS ###
vm_test_curl() {
  if [[ -z "$1" ]]; then
    echo "Usage: $0 <URL>"
    return 1
  fi
  curl -s -o /dev/null -w \
    "dns_lookup: %{time_namelookup}s :: connect: %{time_connect}s :: appconnect: %{time_appconnect}s :: pretransfer: %{time_pretransfer}s :: starttransfer: %{time_starttransfer}s\n-------------------------------\ntotal: %{time_total}s http_code: %{http_code}\n" \
    "$1"
}
alias vm_quick_iperf='docker run -d -it --rm --name=iperf3-server -p 5201:5201 networkstatic/iperf3 -s'
alias vm_test_speed_local='clear && iperf3 -p 5201 -Tl1 -4 -b0 -i3 -O1 -P1 -t0 -c'
alias vm_test_speed_local_docker='clear && docker run -it --rm networkstatic/iperf3 -p 5201 -Tl1 -4 -b0 -i3 -O1 -P1 -t0 -c'
alias vm_test_speed_pub_py='curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python3 - --secure'
# https://github.com/R0GGER/public-iperf3-servers | https://iperf.fr/iperf-servers.php
vm_test_speed_pub() {
  if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <NUM> [ADDITIONAL_IPERF3_PARAMS... (-w128M | -R | -t0 | -4 | -6)]"
    return 1
  fi

  local servers=(
    'a209.speedtest.wobcom.de:5201' # 1
    'a205.speedtest.wobcom.de:5201' # 2
    'speedtest.wobcom.de:5201'      # 3
    'speedtest.myloc.de:5201'       # 4
    'speedtest.lu.buyvm.net:5201'   # 5
    'iperf3.moji.fr:5201'           # 6
    'speedtest.shinternet.ch:5200'  # 7
    'speedtest.init7.net:5201'      # 8
  )

  local num="$1"
  shift
  if ! [[ "$num" =~ ^[0-9]+$ ]] || [ "$num" -lt 1 ] || [ "$num" -gt "${#servers[@]}" ]; then
    num=1
  fi

  local entry="${servers[$((num))]}"
  local server="${entry%%:*}" # Extract server name (before :)
  local port="${entry##*:}"   # Extract port number (after :)

  clear

  local use_docker=0
  if [[ $use_docker -eq 1 ]]; then
    docker run -it --rm networkstatic/iperf3 -c "$server" -p "$port" -Ts1 -b0 -i3 -O1 -P1 "$@"
  else
    iperf3 -c "$server" -p "$port" -Ts1 -b0 -i3 -O1 -P1 "$@"
  fi
}

vm_test_fio() {
  local valid_types=(randread randwrite randrw read write rw)

  if [[ -z "$1" ]] || [[ ! " ${valid_types[*]} " =~ $1 ]]; then
    echo "Usage: $0 <readwrite_type>"
    echo "  <readwrite_type> = ${valid_types[*]}"
    return 1
  fi
  command -v jq >/dev/null || {
    echo "jq is not installed"
    return 1
  }
  command -v fio >/dev/null || {
    echo "fio is not installed"
    return 1
  }

  local FIO_RW_TYPE="$1"
  local FIO_BS="${FIO_BS:-128k}"
  local FIO_IOENGINE="${FIO_IOENGINE:-libaio}"
  local FIO_IODEPTH="${FIO_IODEPTH:-16}"
  local FIO_DIRECT="${FIO_DIRECT:-1}"
  local FIO_NUMJOBS="${FIO_NUMJOBS:-$(($(nproc) / 2))}"
  local FIO_FSYNC="${FIO_FSYNC:-0}"
  local FIO_FILESIZE="${FIO_FILESIZE:-3G}"

  # Check if the FIO_RW_TYPE contains "read" or "write" to set the block size accordingly
  if [[ "$FIO_RW_TYPE" == *"read"* || "$FIO_RW_TYPE" == *"rw"* ]]; then
    FIO_BS="256k"
  elif [[ "$FIO_RW_TYPE" == *"write"* ]]; then
    FIO_BS="1M"
  fi

  echo "Running ${FIO_RW_TYPE} test with block size ${FIO_BS}, ioengine ${FIO_IOENGINE}, iodepth ${FIO_IODEPTH}, direct ${FIO_DIRECT}, numjobs ${FIO_NUMJOBS}, fsync ${FIO_FSYNC}, size ${FIO_FILESIZE}, for 30s..."

  # Initialize variables to store cumulative values
  local OUTPUT
  local TOTAL_READ_IOPS=0
  local TOTAL_WRITE_IOPS=0
  local TOTAL_READ_BW=0
  local TOTAL_WRITE_BW=0

  # Run the FIO benchmark
  OUTPUT=$(fio \
    --rw="$FIO_RW_TYPE" \
    --numjobs="$FIO_NUMJOBS" \
    --time_based \
    --runtime=30s \
    --size="$FIO_FILESIZE" \
    --direct="$FIO_DIRECT" \
    --iodepth="${FIO_IODEPTH}" \
    --bs="$FIO_BS" \
    --group_reporting \
    --fsync="${FIO_FSYNC}" \
    --ioengine="$FIO_IOENGINE" \
    --name="test_$(date +%s%3N)" \
    --filename="fio_test_$FIO_RW_TYPE" \
    --output-format=json)
  # Accumulate values
  TOTAL_READ_IOPS=$(echo "$OUTPUT" | jq '.jobs[0].read.iops + '"$TOTAL_READ_IOPS")
  TOTAL_WRITE_IOPS=$(echo "$OUTPUT" | jq '.jobs[0].write.iops + '"$TOTAL_WRITE_IOPS")
  TOTAL_READ_BW=$(echo "$OUTPUT" | jq '(.jobs[0].read.bw / 1024) + '"$TOTAL_READ_BW")
  TOTAL_WRITE_BW=$(echo "$OUTPUT" | jq '(.jobs[0].write.bw / 1024) + '"$TOTAL_WRITE_BW")

  # Format and print averages, omitting 0 results
  ((${TOTAL_READ_IOPS%.*} > 0)) && echo "Average Read IOPS: $TOTAL_READ_IOPS"
  ((${TOTAL_WRITE_IOPS%.*} > 0)) && echo "Average Write IOPS: $TOTAL_WRITE_IOPS"
  ((${TOTAL_READ_BW%.*} > 0)) && echo "Average Read Bandwidth (MB/s): $TOTAL_READ_BW"
  ((${TOTAL_WRITE_BW%.*} > 0)) && echo "Average Write Bandwidth (MB/s): $TOTAL_WRITE_BW"
}
