#!/usr/bin/env bash

# shellcheck disable=SC1091
source "$HOME/.profile1-base"
source "$HOME/.profile2-defaults"
source "$HOME/.profile3-containers"
source "$HOME/.profile4-helper"
source "$HOME/.profile4-tests"
source "$HOME/.profile5-git"
source "$HOME/.profile6-other"
