# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="spaceship"
#ZSH_THEME="headline"

# # when tmux user installed local bin will needed for plugins
# if [ -d "$HOME/.local/bin" ]; then
#   if [[ ":$PATH:" != *":$HOME/.local/bin:"* ]]; then
#     export PATH="$HOME/.local/bin:$PATH"
#   fi
# fi

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Add wisely, as too many plugins slow down shell startup.
plugins=(colored-man-pages command-not-found docker git gitignore golang helm history kubectl lxd nmap npm oc pip httpie pylint rust sudo terraform ubuntu ufw zsh-autosuggestions zsh-syntax-highlighting)

# disable aliases from oh-my-zsh
zstyle ':omz:lib:*' aliases no

HISTFILE="$HOME/.zsh_history"     # Save them on this file
HISTSIZE=1000000                  # Set the amount of lines you want saved
SAVEHIST=1000000                  # This is required to actually save them, needs to match with HISTSIZE
setopt EXTENDED_HISTORY           # Write the history file in the ":start:elapsed;command" format.
setopt INC_APPEND_HISTORY         # Write to the history file immediately, not when the shell exits.
setopt SHARE_HISTORY              # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST     # Expire duplicate entries first when trimming history.
setopt HIST_IGNORE_DUPS           # Don't record an entry that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS       # Delete old recorded entry if new entry is a duplicate.
setopt HIST_FIND_NO_DUPS          # Do not display a line previously found.
setopt HIST_IGNORE_SPACE          # Don't record an entry starting with a space.
setopt HIST_SAVE_NO_DUPS          # Don't write duplicate entries in the history file.
setopt HIST_REDUCE_BLANKS         # Remove superfluous blanks before recording entry.

source $ZSH/oh-my-zsh.sh
